Simplify wait_for_chain_worker_sync

diff --git a/bash/run_services/chain_worker b/bash/run_services/chain_worker
--- a/bash/run_services/chain_worker
+++ b/bash/run_services/chain_worker
@@ -30,40 +30,25 @@ function startup_chain_worker() {
 }
 
 function wait_for_chain_worker_sync() {
-    local rpc_url="$1"
-    local chain_id="$2"
-    local first_block="$3"
-    local last_block="$4"
+    local rpc_url="$1" chain_id="$2" first_block="$3" last_block="$4"
 
     echo "Waiting for chain worker sync... chain_id=${chain_id} first_block=${first_block} last_block=${last_block}"
 
-    for i in `seq 1 20` ; do
-        local reply=$(curl -s -X POST 127.0.0.1:3001 \
-                  --retry-connrefused \
-                  --retry 5 \
-                  --retry-delay 0 \
-                  --retry-max-time 30 \
-                  -H "Content-Type: application/json" \
-                  --data '{"jsonrpc": "2.0","id": 0,"method": "v_getSyncStatus","params": ['"${chain_id}"']}'
-        )
+    for i in $(seq 1 20); do
+        local reply result first_block_synced last_block_synced
+        reply=$(curl -s -X POST 127.0.0.1:3001 \
+            --retry-connrefused --retry 5 --retry-delay 0 --retry-max-time 30 \
+            -H "Content-Type: application/json" \
+            --data '{"jsonrpc": "2.0", "id": 0, "method": "v_getSyncStatus", "params": ['"${chain_id}"']}')
+        result=$(echo "${reply}" | jq ".result")
 
-        local result=$(echo "${reply}" | jq ".result")
+        if [[ "${result}" != "null" ]]; then
+            first_block_synced=$( [[ "${first_block}" == "latest" ]] || echo "${result}" | jq "(.first_block <= ${first_block})" )
+            last_block_synced=$( [[ "${last_block}" == "latest" ]] || echo "${result}" | jq "(.last_block >= ${last_block})" )
 
-        if [[ "${result}" != "null" ]] ; then
-            local first_block_synced="true"
-            local last_block_synced="true"
-            
-            if [[ "${first_block}" != "latest" ]] ; then
-                first_block_synced=$(echo "${result}" | jq "(.first_block <= ${first_block})")
-            fi
-
-            if [[ "${last_block}" != "latest" ]] ; then
-                last_block_synced=$(echo "${result}" | jq "(.last_block >= ${last_block})")
-            fi
-
-            if [[ "${first_block_synced}" == "true" && "${last_block_synced}" == "true" ]] ; then
-                echo "Chain ${chain_id} worker synced"
-                break
+            if [[ "${first_block_synced}" == "true" && "${last_block_synced}" == "true" ]]; then
+                echo "Chain ${chain_id} worker synced ${result}"
+                return
             fi
         fi
 
@@ -71,8 +56,6 @@ function wait_for_chain_worker_sync() {
         sleep 10
     done
 
-    if [[ "${result}" == "null" || "${first_block_synced}" != "true" || "${last_block_synced}" != "true" ]] ; then
-        echo "Failed to sync chain ${chain_id} worker" >&2
-        exit 1 
-    fi
+    echo "Failed to sync chain ${chain_id} worker" >&2
+    exit 1
 }
