feat: Enable teleport example on sepolia (#2423)

diff --git a/.github/workflows/test_e2e_sepolias.yaml b/.github/workflows/test_e2e_sepolias.yaml
--- a/.github/workflows/test_e2e_sepolias.yaml
+++ b/.github/workflows/test_e2e_sepolias.yaml
@@ -3,6 +3,10 @@ name: E2E test with Bonsai and OP Sepolia
 # This workflow has additional constraints to run on `main`,
 # because it uses external API resources.
 
+# Default network for most E2E tests: Optimism Sepolia (faster & lower gas fees)
+# "simple-teleport" runs on both Optimism Sepolia and Ethereum Sepolia
+# — but only when the on-chain gas price on Ethereum Sepolia is below our configured threshold.
+
 on:
   push:
     branches:
@@ -56,32 +60,53 @@ jobs:
               - '.github/workflows/test_e2e_bonsai_opsepolia.yaml'
               - '.github/actions/test-e2e/**'
 
+  # The gas price on the Ethereum Sepolia network can vary significantly.
+  # To prevent running tests when gas prices are prohibitively high, this job checks the current gas price.
+  # If the gas price exceeds a predefined threshold, the test is skipped to avoid running out of test eth.
+  # Gas price checker is build using `build-gas-price-checker` job. It's code is in
+  # `rust/zkvm-benchmarks/benchmarks/src/benchmarks/precompiles/gas_price_checker.rs`
   check-gas:
-    name: Check Gas Price
+    name: Check gas price
     runs-on: ubuntu-latest
     outputs:
       gas-ok: ${{ steps.set-result.outputs.gas-ok }}
     steps:
-      - name: Download gas_price_checker from S3
-        uses: keithweaver/aws-s3-github-action@v1.0.0
+      - name: Configure AWS creds
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          command: cp
-          source: "s3://${{ vars.AWS_BUCKET }}/gas_price_checker"
-          destination: ./gas_price_checker
-          aws_access_key_id: ${{ vars.AWS_ACCESS_KEY_ID }}
-          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws_region: eu-north-1
+          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-north-1
 
-      - name: Run gas price checker
-        id: check
-        continue-on-error: true
+      - name: Download gas_price_checker from S3
         run: |
-          ./gas_price_checker https://eth-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }} 5
+          aws s3 cp \
+            s3://${{ vars.AWS_BUCKET }}/gas_price_checker \
+            "$RUNNER_TEMP/gas_price_checker"
+      - name: Make gas_price_checker executable
+        run: sudo chmod +x "$RUNNER_TEMP/gas_price_checker"
+
+      - name: Run gas_price_checker
+        id: run-check
+        run: |
+          # allow failure so we can capture it
+          set +e
+          "$RUNNER_TEMP/gas_price_checker" \
+            "https://eth-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}" \
+            $GAS_PRICE_THRESHOLD
+          EXIT_CODE=$?
+          echo "exit_code=$EXIT_CODE" >>"$GITHUB_OUTPUT"
+        env:
+          GAS_PRICE_THRESHOLD: 20
 
       - name: Set gas check result
         id: set-result
         run: |
-          echo "gas-ok=${{ steps.check.outcome == 'success' }}" >>"$GITHUB_OUTPUT"
+          if [ "${{ steps.run-check.outputs.exit_code }}" = "0" ]; then
+            echo "gas-ok=true" >>"$GITHUB_OUTPUT"
+          else
+            echo "gas-ok=false" >>"$GITHUB_OUTPUT"
+          fi
 
   build-binaries:
     name: Build binaries
@@ -240,3 +265,24 @@ jobs:
           chain_name: "optimismSepolia"
           testnet_private_key_location: ${{ secrets.TESTNET_PRIVATE_KEY_LOCATION }}
           quicknode_api_key: ${{ secrets.QUICKNODE_API_KEY }}
+
+  # We run simple-teleport using test chain service, which generates fake proofs.
+  # It is not compatible with Bonsai, which expects "prod" proofs, so we don't test teleport on Bonsai.
+  test-e2e-ethsepolia-simple-teleport:
+    name: E2E test (simple-teleport) with Sepolia
+    needs: [changes, check-gas, build-binaries]
+    if: needs.check-gas.outputs.gas-ok == 'true'
+    runs-on: aws-linux-medium
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Run E2E Test
+        uses: ./.github/actions/test-e2e
+        env:
+          RUST_LOG: info
+        with:
+          example: "simple-teleport"
+          chain_name: "sepolia"
+          testnet_private_key_location: ${{ secrets.TESTNET_PRIVATE_KEY_LOCATION }}
+          quicknode_api_key: ${{ secrets.QUICKNODE_API_KEY }}
+          external_chain_service_url: "https://test-chainservice.vlayer.xyz"
